sudo: false

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.8
          - g++-4.8
          - libboost-all-dev
      env:
        - CC=gcc-4.8
        - CXX=g++-4.8
        
        # set environment variables for boost
        - CASM_BOOST_INCLUDEDIR="/usr/include/"
        - CASM_BOOST_LIBDIR="/usr/lib/x86_64-linux-gnu/"
        - CASM_BOOST_NO_CXX11_SCOPED_ENUMS=1

    - os: osx
      compiler: clang
      env:
        - CASM_BOOST_NO_CXX11_SCOPED_ENUMS=1
        

before_install:

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
        CASM_NCPU=2;
    fi
  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
        brew install boost@1.55;
        CASM_NCPU=2;
    fi
  
  # check g++ version
  - g++ --version
  
  # check python
  - python --version
  - python -c "import sys; print sys.path"
  
  # get scons-2.5.1
  - wget http://prdownloads.sourceforge.net/scons/scons-2.5.1.tar.gz
    && tar -xzf scons-2.5.1.tar.gz
    && cd scons-2.5.1
    && python setup.py install --user --prefix=
    && cd ..
  - export PYINSTALL=`python -m site --user-site`
  - export BIN="$PYINSTALL/../../../bin"
  - echo $PYINSTALL
  - echo $BIN
  - export PATH=$BIN:$PATH
  - export PYTHONPATH=$PYINSTALL:$PYTHONPATH
  - scons --version
  
  # install other python dependencies
  - pip install --upgrade pip
  - pip install --user -r python/casm/requirements.txt
  
  # install pbs
  - git clone https://github.com/prisms-center/pbs.git
  - cd pbs && git checkout v2.0.0 && make install && cd ..  
  - unset BIN
  - unset PYINSTALL
  
  # check env
  - printenv
  

script: 
  - set -e
  - 'echo "CASM_NCPU: $CASM_NCPU"'
  - scons configure
  - scons -j $CASM_NCPU
  - scons unit -j $CASM_NCPU
